let employee = {
    CreatedDate: Date,
    CreatedBy: "",
    ModifiedDate: Date,
    ModifiedBy: "",
    EmployeeCode: "",
    FirstName: "",
    LastName: "",
    FullName: "",
    Gender: Number,
    DateOfBirth: Date,
    PhoneNumber: "",
    Email: "",
    Address: "",
    IdentityNumber: "",
    IdentityDate: Date,
    IdentityPlace: "",
    JoinDate: Date,
    MartialStatus: Number,
    EducationalBackground: 0,
    QualificationId: null,
    DepartmentId: null,
    PositionId: null,
    WorkStatus: Number,
    PersonalTaxCode: "",
    Salary: 0,
    PositionCode: "",
    PositionName: "",
    DepartmentCode: "",
    DepartmentName: "",
    QualificationName: null,
}
export default employee